// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0H2phvAy0kJl_PGP2dXMRIApyt4WcdhU',
    appId: '1:480646527179:web:3cc3f1dd4e6517330f034e',
    messagingSenderId: '480646527179',
    projectId: 'webtasksinglepage',
    authDomain: 'webtasksinglepage.firebaseapp.com',
    storageBucket: 'webtasksinglepage.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4qnUpIYNeIu0k_GxjjYwxLHPv6RiZtLM',
    appId: '1:480646527179:android:63828473f723fc760f034e',
    messagingSenderId: '480646527179',
    projectId: 'webtasksinglepage',
    storageBucket: 'webtasksinglepage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCokLsokV_vbH2n2Y8ubg3TMvJvGqhQ_o',
    appId: '1:480646527179:ios:03de99e69418cb7f0f034e',
    messagingSenderId: '480646527179',
    projectId: 'webtasksinglepage',
    storageBucket: 'webtasksinglepage.appspot.com',
    iosBundleId: 'com.example.webappTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCokLsokV_vbH2n2Y8ubg3TMvJvGqhQ_o',
    appId: '1:480646527179:ios:03de99e69418cb7f0f034e',
    messagingSenderId: '480646527179',
    projectId: 'webtasksinglepage',
    storageBucket: 'webtasksinglepage.appspot.com',
    iosBundleId: 'com.example.webappTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0H2phvAy0kJl_PGP2dXMRIApyt4WcdhU',
    appId: '1:480646527179:web:1135f65bb328fac10f034e',
    messagingSenderId: '480646527179',
    projectId: 'webtasksinglepage',
    authDomain: 'webtasksinglepage.firebaseapp.com',
    storageBucket: 'webtasksinglepage.appspot.com',
  );
}
